# Generated by Django 4.0.5 on 2022-06-18 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mlm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OwnerCategory', models.CharField(max_length=90, verbose_name='ownercategory')),
                ('MlmOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userOwner', to=settings.AUTH_USER_MODEL)),
                ('MlmUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
