# Generated by Django 4.0.5 on 2022-06-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0002_userowner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OwnerCategory', models.CharField(max_length=90, verbose_name='ownercategory')),
            ],
        ),
        migrations.RemoveField(
            model_name='userowner',
            name='OwnerCategory',
        ),
    ]
