# Generated by Django 4.0.5 on 2022-06-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0003_category_remove_userowner_ownercategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellingPursant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(verbose_name='point')),
                ('differ', models.IntegerField(verbose_name='differ')),
                ('coefficient', models.IntegerField(verbose_name='coefficient')),
            ],
        ),
    ]
