# Generated by Django 4.0.5 on 2022-06-25 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mlm', '0006_compress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group',
        ),
        migrations.DeleteModel(
            name='SellingPursant',
        ),
        migrations.RenameField(
            model_name='compress',
            old_name='compress',
            new_name='CMlmUser',
        ),
        migrations.AddField(
            model_name='compress',
            name='CMlmOwner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Compress', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
