# Generated by Django 4.0.5 on 2022-06-25 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mlm', '0007_remove_group_group_delete_sellingpursant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compress',
            name='CMlmOwner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Compress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userowner',
            name='MlmOwner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userOwner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userowner',
            name='MlmUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
