# Generated by Django 4.0.5 on 2022-06-26 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mlm', '0008_alter_compress_cmlmowner_alter_userowner_mlmowner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
